### ISSUE TITLE
The demo4_train_LRBP does not include the file of bisvm_posneg_UUreg_forward/backward ? Can you provide?

### ISSUE THREAD

**Issue by ZBYuan0813** [aimerykong/Low-Rank-Bilinear-Pooling#3]

**Comment by aimerykong** [comment]
I've uploaded the two file to this folder --

https://github.com/aimerykong/Low-Rank-Bilinear-Pooling/tree/master/demo4_train_LRBP/froBiCls

Thanks.

**Comment by ZBYuan0813** [comment]
Thank you !

**Comment by shiyuanyin** [comment]
@aimerykong 
Hi ,thank you for your paper work ,is great.
but I have some question to ask for your help.
1.  I still don't know the vgg16 param m =100,r=8,  how to get the m .If I change the model or dataset, how should I calculate these values? 
2. I'm sorry your formula calculation is a little hard for me to understand. Could you provide me some easy understand imformation or paper? I want to know how to infer formulas.

For our model, we set m= 100 and r= 8, corresponding to the reduced feature dimension and the rank of our low-rank classifier, respectively

Thank you for your reply(If you are more familiar with Chinese ，You can reply in Chinese for me ）

**Comment by shiyuanyin** [comment]
@aimerykong 
I think your visilization is cool ,I also want to realise it.Could you provide me with relevant information and code?
5.5. Qualitative Visualization
To better understand our model,  we adopt three differ-ent approaches to visualizing the model response for spe-cific  input  images.
