### ISSUE TITLE
What modified in folder named "caffe-20160312"

### ISSUE THREAD

**Issue by jnulzl** [aimerykong/Low-Rank-Bilinear-Pooling#5]
Hello,@aimerykong ,you mentioned "**The folder named "caffe-20160312" is a modified caffe toolbox by Yang Gao for his "compact bilinear pooling**"" in readme.md. I want to know where are you modified, Could you tell me please??

**Comment by aimerykong** [comment]
Hi, 
Thanks for your interest! I didn't modify the caffe toolbox, which is modified by Yang:-) I implement my method with matconvnet and merely use the modified caffe for fast demonstration (as caffe operates faster than matlab:-)

**Comment by jnulzl** [comment]
OK, Thank you!!

**Comment by jnulzl** [comment]
OK,Thank you!
